<?php

namespace Tests\Unit\Mobile\V3\Partners;

use Tests\TestCase;

class MFOOrderTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
//        $token = "898acbf3de56bda4e2afe2be41b3add3"; //simple partner token
        $token = "42bc5fab701e8f3ffdd126fb88643fcb"; //general partner token
        $this->withHeaders([
            "Content-Type" => "application/json",
            "Authorization" => "Bearer {$token}"
        ]);
    }

    public function test_auth()
    {
        $result = $this->postJson('api/v3/auth', [
            'partner_id' => '215351',
            'password' => 'GKbpD4fddxBV',
        ]);

        $result->dump();
    }

    public function test_order_mfo_add()
    {
        $result = $this->postJson('api/v3/mfo/order', [
            "user_id" => 758234,
            "period" => '003',
            "products" => [
                [
                    "unit_id" => 1,
                    "category" => 3,
                    "amount" => "1",
                    "name" => "Product 1",
                    "imei" => "213421341234134",
                    "product_id" => 6256,
                    "price" => 1000
                ]
            ]
        ]);
        $result->dump();
    }

    public function test_order_calculate()
    {
        $result = $this->postJson('api/v3/mfo/calculate', [
            "user_id" => 96,
            "period" => '0-0-3',
            "products" => [
                [
                    "price" => 1000,
                    "amount" => 1,
                    "product_id" => 1
                ],
                [
                    "price" => 2000,
                    "amount" => 4,
                    "product_id" => 5
                ]
            ]
        ]);
        $result->dump();
    }

    public function test_check_contract_status()
    {
        $result = $this->postJson('api/v3/mfo/check-status', [
            "contract_id" => 64251
        ]);
        $result->dump();
    }

    public function test_activate_sms_code()
    {
        $result = $this->postJson('api/v3/mfo/activate-sms/send', [
            "contract_id" => 64251
        ]);
        $result->dump();
    }

    public function test_send_code() {
        $result = $this->postJson('api/v3/kyc/docs', [
            "contract_id" => 64251
        ]);
        $result->dump();
    }
}
