<?php

namespace Mobile\V3;

use App\Services\Mobile\AppReleaseVersion\AppReleaseVersionService;
use Tests\TestCase;

class AppReleaseTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withHeaders([
            "Content-Type" => "application/json",
            'x-mobile-version' => '2.1.1',
            'x-mobile-os' => AppReleaseVersionService::OS_ANDROID,
            'x-mobile-build' => AppReleaseVersionService::ANDROID_CLIENT_BUNDLE_NAME,
        ]);
    }

    public function test_get_mobile_app_release()
    {
        $response = $this->getJson(
            'api/v3/app-version',
        );
        $response->dump();
        $response->assertStatus(200);
    }
}
