<?php

namespace Tests\Unit\Mobile\V3;

use App\Models\V3\OtpEnterCodeAttempts;
use Tests\TestCase;

class AuthTest extends TestCase
{

    const TOKEN = "d68a0ee2f67274ca7917661463cf7233";

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $token = self::TOKEN;
        $this->phone = "998973307880";
        $this->withHeaders([
            "Content-Type" => "application/json",
            "Authorization" => "Bearer {$token}"
        ]);
    }

    public function test_sign_in_send_sms()
    {
        $response = $this->postJson(
            'api/v3/login/send-sms-code',
            [
                "phone" => $this->phone,
            ]
        );
        $response->dump();
        $response->assertStatus(200);
    }

    public function test_sign_in_check_sms()
    {
        $code = OtpEnterCodeAttempts::where('phone', $this->phone)->first()->code;

        $response = $this->postJson(
            '/api/v3/login/auth',
            [
                "phone" => $this->phone,
                "code" => $code,
            ]
        );
        $response->dump();
        $response->assertStatus(200);
    }
}
