<?php

namespace Tests\Unit\Mobile\V3;

class BuyerTest extends AuthTest
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $token = '8a31154dcea4185da1c69838956c3b3c';
        $this->phone = "998973307880";
        $this->withHeaders([
            "Content-Type" => "application/json",
            "Authorization" => "Bearer {$token}",
            "Content-language" => "uz"
        ]);
    }

    public function test_get_contracts()
    {
        $response = $this->getJson(
            'api/v3/buyer/contracts'
        );
        $response->dump();
        $response->assertStatus(200);
    }


    public function test_get_buyer_limits()
    {
        $response = $this->getJson(
            'api/v3/buyer/limits'
        );
        $response->dump();
        $response->assertStatus(200);
    }
}
