<?php

namespace Mobile\V3;

use Tests\TestCase;

class ContractsTest extends TestCase
{
  protected function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
        $token = "42bc5fab701e8f3ffdd126fb88643fcb"; //simple partner token
//    $token = "6df394f91b0bdbae70446c4b9551f56a"; //general partner token
    $this->withHeaders([
      "Content-Type" => "application/json",
      "Authorization" => "Bearer {$token}"
    ]);
  }


  public function test_auth()
  {
    $result = $this->postJson('api/v3/auth', [
      'partner_id' => '215351',
      'password' => 'GKbpD4fddxBV',
    ]);

    $result->dump();
  }


  public function test_get_order_list()
  {
    $result = $this->get('api/v3/order/list');
    $result->dump();
  }


  public function test_order_add()
  {
    $result = $this->postJson('api/v3/orders/add', [
      "user_id" => 373169,
      "period" => 6,
      "products" => [
        [
          "category" => 1331,
          "amount" => "1",
          "name" => "Product 1",
          "imei" => "213421341234134",
          "price" => 10000
        ],
        [
          "category" => 1331,
          "amount" => "1",
          "name" => "Product 2",
          "imei" => "213421341234134",
          "price" => 50000
        ]
      ]
    ]);
    $result->dump();
  }

  public function test_send_cancellation_request()
  {

    $result = $this->postJson('api/v3/contracts/create-cancel-request', [
      'contract_id' => '1235547',
      'reason' => 'Вот так вот захотелось'
    ]);

    $result->dump();

    $result->assertStatus(200);
  }

  public function test_reject_cancellation_request()
  {

    $result = $this->postJson('api/v3/contracts/reject-cancel-request', [
      'contract_id' => '1235547',
    ]);

    $result->dump();

    $result->assertStatus(200);
  }


  public function test_send_sms_code_from_cancellation_request()
  {

    $result = $this->postJson('api/v3/contracts/send-cancel-sms', [
      'contract_id' => '1235547',
    ]);

    $result->dump();
  }


  public function test_get_phone_counts()
  {

    $result = $this->json('GET','api/v3/buyer/phones-count',[
      'buyer_id' => 373169
    ]);

    $result->dump();
  }


  public function test_get_partner_detail_information() {
    $result = $this->get('api/v3/partner/detail');
    $result->dump();

    $result->assertStatus(200);
  }


}
