<?php

namespace Mobile\V3;

use Tests\TestCase;

class OrdersTest extends TestCase
{
    const TOKEN = "fc79cad0e8385334dab0d756731d4ed0";

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $token = self::TOKEN;
        $this->withHeaders([
            "Content-Type" => "application/json",
            "Authorization" => "Bearer {$token}"
        ]);
    }


    public function test_create_order()
    {
        $result = $this->postJson('/api/v3/orders/add', [
            "user_id" => 372361,
            "period" => 12,
            "products" => [
              [
                "unit_id" => "3",
                "category" => 1330,
                "amount" => "1",
                "name" => "Product 1",
                "imei" => "213421341234134",
                "price" => '10000'
              ],
              [
                "unit_id" => 2,
                "category" => 1320,
                "amount" => "2",
                "name" => "Product 2",
                "imei" => "213421341234134",
                "price" => '30000'
              ]
            ]
     ]);

        $result->dump();

        $result->assertStatus(200);


    }

}
