<?php

namespace Tests\Unit\Services;

use Tests\TestCase;

class PaymentServiceTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $token = "42bc5fab701e8f3ffdd126fb88643fcb"; //simple partner token
//    $token = "6df394f91b0bdbae70446c4b9551f56a"; //general partner token
        $this->withHeaders([
            "Content-Type" => "application/json",
            "Authorization" => "Bearer {$token}"
        ]);
    }

    public function test_make_transaction()
    {
        $result = $this->postJson('api/v3/admin/transaction/make', [
            'amount' => 10,
            'account' => '20208000905369234001',
//            'account' => '20208000905369234002',
//            'account' => '22228000905392340001',
            'mfo' => '00974',
            'name' => 'АО SOLUTIONS LAB',
            'detail' => 'Тест тест',
        ]);

        $result->dump();
    }

    public function test_list_transaction()
    {
        $result = $this->getJson('api/v3/admin/transaction/list');
        $result->dump();
    }

    public function test_get_transaction_config()
    {
        $result = $this->getJson('api/v3/admin/transaction/config');
        $result->dump();
    }

}
